# Generated by Django 3.1.5 on 2021-01-13 10:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_auto_20210112_0343')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatBreed',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=60, verbose_name='Breed Origin')),
                ('temperament', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Temperament'), blank=True, default=list, size=None)),
                ('description', models.TextField(verbose_name='Description')),
                ('name', models.CharField(default='', max_length=40, verbose_name='Breed Name')),
            ],
        ),
    ]
