# Generated by Django 3.1.5 on 2021-01-11 12:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatBreed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=60, verbose_name='Breed Origin')),
                ('temperament', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Temperament'), blank=True, default=[], size=None)),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
