# Generated by Django 3.1.5 on 2021-01-12 03:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catbreed',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='Breed Name'),
        ),
        migrations.AlterField(
            model_name='catbreed',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catbreed',
            name='temperament',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Temperament'), blank=True, default=list, size=None),
        ),
    ]
