global:
  scrape_interval: 5s
  evaluation_interval: 5s

  external_labels:
    monitor: catservable-monitor

rule_files:
- "django.rules"

scrape_configs:
- job_name: "django"
  static_configs:
  - targets: ["api:8000"]
