{
 "title": "SRE Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(django_http_requests_total_by_view_transport_method_total{view!=\"prometheus-django-metrics\"})"
    }
   ]
  },
  {
   "title": "Error count",
   "type": "stat",
   "description": "Count anything that is not 2XX or 3XX",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(django_http_responses_total_by_status_view_method_total{view!=\"prometheus-django-metrics\", status!=\"200\"})"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "description": "Request Latency per view",
   "gridPos": { "h": 10, "w": 16, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(django_http_requests_latency_seconds_by_view_method_count{view!=\"prometheus-django-metrics\"}[5m])",
     "legendFormat": "{{view}}"
    }
   ]
  }
 ]
}